pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      # - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-coverage
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports
  type: publish
  image: plugins/drone-coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
